import Link from "next/link";
import { ArrowRight, CopyPlus, FilePlus2, Settings2 } from "lucide-react";
import { cloneCheckTemplate, createCheckTemplate } from "@/app/actions/check-templates";
import { requireActualRole } from "@/lib/auth/dal";
import { getCheckTemplateAdminDirectory } from "@/lib/data/check-template-admin";

export const metadata = { title: "Kitchen check templates" };

export default async function CheckTemplatesPage() {
  await requireActualRole(["admin", "group_manager"]);
  const { templates, sites } = await getCheckTemplateAdminDirectory();
  const activeTemplates = templates.filter((item) => item.active);

  return (
    <>
      <header className="page-header"><div><p className="page-header__eyebrow">Compliance administration</p><h1 className="page-header__title">Check templates.</h1><p className="page-header__copy">Create a kitchen-specific daily or weekly check, clone a proven template, then customise every section and standard.</p></div><Link className="button button--secondary" href="/checks">Back to checks</Link></header>
      <div className="dashboard-grid dashboard-grid--balanced">
        <section className="panel"><div className="panel__header"><div><h2 className="panel__title">Create blank template</h2><p className="panel__subtitle">Start from zero for a genuinely different kitchen workflow</p></div><FilePlus2 aria-hidden="true" size={19} /></div><form action={createCheckTemplate} className="panel__body report-form"><label className="field"><span className="field__label">Kitchen</span><select className="field__input" name="siteId" required><option value="">Choose kitchen</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><div className="form-grid form-grid--two"><label className="field"><span className="field__label">Template name</span><input className="field__input" name="name" placeholder="Daily Kitchen Check" required /></label><label className="field"><span className="field__label">Cadence</span><select className="field__input" defaultValue="daily" name="cadence"><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label></div><label className="field"><span className="field__label">Description</span><textarea className="field__input" name="description" rows={3} /></label><div className="form-grid form-grid--two"><label className="field"><span className="field__label">Pass threshold %</span><input className="field__input" defaultValue="90" max="100" min="1" name="passThreshold" step="0.1" type="number" /></label><label className="field"><span className="field__label">Watch threshold %</span><input className="field__input" defaultValue="75" max="99" min="0" name="watchThreshold" step="0.1" type="number" /></label></div><button className="button button--primary" type="submit"><FilePlus2 aria-hidden="true" size={15} /> Create and edit</button></form></section>
        <section className="panel"><div className="panel__header"><div><h2 className="panel__title">Clone existing template</h2><p className="panel__subtitle">Copy sections and standards into a new independent site template</p></div><CopyPlus aria-hidden="true" size={19} /></div><form action={cloneCheckTemplate} className="panel__body report-form"><label className="field"><span className="field__label">Source template</span><select className="field__input" name="sourceTemplateId" required><option value="">Choose source</option>{activeTemplates.map((template) => <option key={template.id} value={template.id}>{template.siteName} · {template.name}</option>)}</select></label><label className="field"><span className="field__label">Destination kitchen</span><select className="field__input" name="targetSiteId" required><option value="">Choose kitchen</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label className="field"><span className="field__label">New template name</span><input className="field__input" name="name" placeholder="Kardia Daily Kitchen Check" required /></label><button className="button button--primary" type="submit"><CopyPlus aria-hidden="true" size={15} /> Clone and customise</button></form></section>
      </div>
      <section className="panel"><div className="panel__header"><div><h2 className="panel__title">Template register</h2><p className="panel__subtitle">Every active and archived site template</p></div><Settings2 aria-hidden="true" size={19} /></div><div className="report-list">{templates.map((template) => <Link className="report-row" href={`/checks/templates/${template.id}`} key={template.id}><div className="site-cell"><div className="site-cell__mark">{template.cadence === "daily" ? "D" : "W"}</div><div><div className="site-cell__name">{template.name}</div><div className="site-cell__manager">{template.siteName} · v{template.version}</div></div></div><div><span className="report-row__metric-label">Structure</span>{template.sectionCount} sections · {template.itemCount} checks</div><div><span className="report-row__metric-label">Thresholds</span>{template.passThreshold}% pass · {template.watchThreshold}% watch</div><span className={`status-badge status-badge--${template.active ? "approved" : "draft"}`}>{template.active ? "Active" : "Archived"}</span><ArrowRight aria-hidden="true" size={15} /></Link>)}{!templates.length ? <div className="empty-inline">No templates exist yet.</div> : null}</div></section>
    </>
  );
}
